#import "DYSettings.h"
#import "DYConfig.h"
#import "DYWebDAV.h"
@implementation DYSettings
+ (void)field:(UITextField **)outField title:(NSString *)title value:(NSString *)value secure:(BOOL)secure inController:(UIViewController *)vc completion:(void (^)(NSString *))done { UIAlertController *a=[UIAlertController alertControllerWithTitle:title message:nil preferredStyle:UIAlertControllerStyleAlert]; [a addTextFieldWithConfigurationHandler:^(UITextField*f){f.text=value;f.secureTextEntry=secure;}]; [a addAction:[UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStyleCancel handler:nil]]; [a addAction:[UIAlertAction actionWithTitle:@"保存" style:UIAlertActionStyleDefault handler:^(UIAlertAction*x){done(a.textFields.firstObject.text ?: @"");}]]; [vc presentViewController:a animated:YES completion:nil]; }
+ (void)presentFrom:(UIViewController *)vc { UIAlertController *a=[UIAlertController alertControllerWithTitle:@"DYYYWebDAV 设置" message:@"逐项配置，保存后立即生效" preferredStyle:UIAlertControllerStyleActionSheet]; DYConfig *c=[DYConfig shared];
    [a addAction:[UIAlertAction actionWithTitle:@"解析 API" style:UIAlertActionStyleDefault handler:^(UIAlertAction*x){[self field:nil title:@"解析 API（支持 {url}）" value:c.apiURL secure:NO inController:vc completion:^(NSString*v){c.apiURL=v;[c save];}];}]];
    [a addAction:[UIAlertAction actionWithTitle:@"WebDAV 地址" style:UIAlertActionStyleDefault handler:^(UIAlertAction*x){[self field:nil title:@"WebDAV 地址" value:c.webdavURL secure:NO inController:vc completion:^(NSString*v){c.webdavURL=v;[c save];}];}]];
    [a addAction:[UIAlertAction actionWithTitle:@"WebDAV 用户名" style:UIAlertActionStyleDefault handler:^(UIAlertAction*x){[self field:nil title:@"用户名" value:c.username secure:NO inController:vc completion:^(NSString*v){c.username=v;[c save];}];}]];
    [a addAction:[UIAlertAction actionWithTitle:@"WebDAV 密码" style:UIAlertActionStyleDefault handler:^(UIAlertAction*x){[self field:nil title:@"密码" value:c.password secure:YES inController:vc completion:^(NSString*v){c.password=v;[c save];}];}]];
    [a addAction:[UIAlertAction actionWithTitle:@"远程目录" style:UIAlertActionStyleDefault handler:^(UIAlertAction*x){[self field:nil title:@"远程目录" value:c.remotePath secure:NO inController:vc completion:^(NSString*v){c.remotePath=v;[c save];}];}]];
    [a addAction:[UIAlertAction actionWithTitle:@"测试 WebDAV" style:UIAlertActionStyleDefault handler:^(UIAlertAction*x){[DYWebDAV testConnection:^(BOOL ok,NSString*msg){dispatch_async(dispatch_get_main_queue(),^{UIAlertController*b=[UIAlertController alertControllerWithTitle:ok?@"连接成功":@"连接失败" message:msg preferredStyle:UIAlertControllerStyleAlert];[b addAction:[UIAlertAction actionWithTitle:@"好" style:UIAlertActionStyleDefault handler:nil]];[vc presentViewController:b animated:YES completion:nil];});}];}]];
    [a addAction:[UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStylecancel handler:nil]]; if(UI_USER_INTERFACE_IDIOM()==UIUserInterfaceIdiomPad){a.popoverPresentationController.sourceView=vc.view;a.popoverPresentationController.sourceRect=CGRectMake(vc.view.bounds.size.width/2,vc.view.bounds.size.height/2,1,1);} [vc presentViewController:a animated:YES completion:nil]; }
@end
